[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
decorations = "none"
blur = true
padding = { x = 8, y = 8 }
dynamic_padding = false
startup_mode = "Windowed"
title = "terminal"
dynamic_title = false

[font]
normal = { family = "Gohu GohuFont", style = "Regular" }
bold = { family = "Gohu GohuFont", style = "Bold" }
italic = { family = "Gohu GohuFont", style = "Italic" }
size = 11.0
offset = { x = 0, y = 0 }

[colors.primary]
background = "0x0f0f0f"
foreground = "0xeceff4"  # soft white

[colors.cursor]
text = "0x0f0f0f"
cursor = "0x88c0d0"  # pastel blue

[colors.selection]
text = "0x0f0f0f"
background = "0x88c0d0"

[colors.normal]
black   = "0x2e3440"
red     = "0xeb6f92"  # pastel red/pink
green   = "0xa3be8c"  # pastel green
yellow  = "0xf6c177"  # pastel yellow/orange
blue    = "0x88c0d0"  # pastel blue
magenta = "0xd08770"  # pastel peach
cyan    = "0x81a1c1"  # muted cyan
white   = "0xe5e9f0"

[colors.bright]
black   = "0x4c566a"
red     = "0xeb6f92"
green   = "0xb8d694"
yellow  = "0xf6c177"
blue    = "0x8fbcbb"
magenta = "0xe49b71"
cyan    = "0x9ccfd8"
white   = "0xffffff"


[cursor]
style = "Beam"
unfocused_hollow = true

[selection]
save_to_clipboard = true
