[env]
# Optional: For consistent behavior with CLI tools
TERM = "xterm-256color"

[window]
opacity = 0.9
decorations = "none"
blur = true
padding = { x = 8, y = 8 }
dynamic_padding = false
startup_mode = "Windowed"

[font]
normal = { family = "Gohu GohuFont", style = "Regular" }
bold = { family = "Gohu GohuFont", style = "Bold" }
italic = { family = "Gohu GohuFont", style = "Italic" }
size = 11.0

[colors.primary]
background = "0x0f0f0f"
foreground = "0xffffff"

[colors.cursor]
text = "0x0f0f0f"
cursor = "0x66ccff"

[colors.selection]
text = "0x0f0f0f"
background = "0x66ccff"

[colors.normal]
black   = "0x000000"
red     = "0xfd5753"
green   = "0x4ef499"
yellow  = "0xdaef4d"
blue    = "0x66ccff"
magenta = "0xfb9d4b"
cyan    = "0xa3d4f7"
white   = "0xe0e0e0"

[colors.bright]
black   = "0x444444"
red     = "0xfd5753"
green   = "0x52f298"
yellow  = "0xdaef4d"
blue    = "0x66ccff"
magenta = "0xfb9d4b"
cyan    = "0xa3d4f7"
white   = "0xffffff"

[cursor]
style = "Beam"

[selection]
save_to_clipboard = true
